// Generated by VexaScript. Compile through `vexa build <file> --emit cpp --native`.
#include "runtime.cpp"

class Meter;
class Greeter;
class Leaf;
class Counter;
class English;
class Spanish;
class NumberBox;
class Bag;
class Animal;
class Dog;

struct Permission final {
  static constexpr std::int32_t None = 0;
  static constexpr std::int32_t Read = 1;
  static constexpr std::int32_t Write = (Read << 1);
  static constexpr std::int32_t All = (Read | Write);
};

class Meter : public cppgc::GarbageCollectedMixin {
 public:
  virtual ~Meter() = default;
  void Trace(cppgc::Visitor*) const override {}
  virtual std::int32_t __vexa_property_get_value(vexa::Runtime& __vexa_runtime) = 0;
  virtual void __vexa_property_set_value(vexa::Runtime& __vexa_runtime, std::int32_t value) = 0;
  virtual vexa::Value __vexa_property_get_label(vexa::Runtime& __vexa_runtime) = 0;
  virtual Leaf* __vexa_property_get_leaf(vexa::Runtime& __vexa_runtime) = 0;
  virtual std::int32_t add(vexa::Runtime& __vexa_runtime, std::int32_t delta) = 0;
};
class Greeter : public cppgc::GarbageCollectedMixin {
 public:
  virtual ~Greeter() = default;
  void Trace(cppgc::Visitor*) const override {}
  virtual vexa::Value greet(vexa::Runtime& __vexa_runtime, vexa::Value prefix) = 0;
};

std::int32_t importedDouble(vexa::Runtime& __vexa_runtime, std::int32_t value);
vexa::Value importedLabel(vexa::Runtime& __vexa_runtime);
vexa::Value render(vexa::Runtime& __vexa_runtime, Meter* meter);
vexa::Value greet(vexa::Runtime& __vexa_runtime, Greeter* greeter, vexa::Value prefix);
std::int32_t add(vexa::Runtime& __vexa_runtime, std::int32_t value, std::int32_t delta);
std::int32_t sumDown(vexa::Runtime& __vexa_runtime, std::int32_t value);
vexa::Value classify(vexa::Runtime& __vexa_runtime, vexa::Value value);
std::int32_t guarded(vexa::Runtime& __vexa_runtime);
std::int32_t loopControl(vexa::Runtime& __vexa_runtime);
vexa::Generator<std::int32_t> sequence(vexa::Runtime& __vexa_runtime, std::int32_t limit);
vexa::Task<std::int32_t> asyncValue(vexa::Runtime& __vexa_runtime);
vexa::Task<std::int32_t> doubledAsync(vexa::Runtime& __vexa_runtime);
vexa::Task<vexa::Value> delay(vexa::Runtime& __vexa_runtime, double ms);

class Leaf final : public cppgc::GarbageCollected<Leaf> {
 public:
  Leaf(std::int32_t value) : value(value) {}
  void Trace(cppgc::Visitor*) const {}
  const std::int32_t value;
};
class Counter final : public cppgc::GarbageCollected<Counter>, public Meter {
 public:
  Counter(std::int32_t value, vexa::Value label, Leaf* leaf) : value(value), label(label), leaf(leaf) {}
  void Trace(cppgc::Visitor* visitor) const final { Meter::Trace(visitor); visitor->Trace(leaf); }
  std::int32_t value;
  const vexa::Value label;
  const cppgc::Member<Leaf> leaf;
  std::int32_t __vexa_property_get_value(vexa::Runtime&) override { return this->value; }
  void __vexa_property_set_value(vexa::Runtime&, std::int32_t __vexa_property_value) override { this->value = __vexa_property_value; }
  vexa::Value __vexa_property_get_label(vexa::Runtime&) override { return this->label; }
  Leaf* __vexa_property_get_leaf(vexa::Runtime&) override { return this->leaf; }
  std::int32_t add(vexa::Runtime& __vexa_runtime, std::int32_t delta) override {
    try {
      (this->value += delta);
      return this->value;
    }
    catch (const vexa::ReturnSignal<std::int32_t>& __vexa_return) { return __vexa_return.value(); }
  }
  std::int32_t addAgain(vexa::Runtime& __vexa_runtime, std::int32_t delta) {
    try {
      return this->add(__vexa_runtime, delta);
    }
    catch (const vexa::ReturnSignal<std::int32_t>& __vexa_return) { return __vexa_return.value(); }
  }
};
class English final : public cppgc::GarbageCollected<English>, public Greeter {
 public:
  English(vexa::Value name) : name(name) {}
  void Trace(cppgc::Visitor* visitor) const final { Greeter::Trace(visitor); }
  const vexa::Value name;
  vexa::Value greet(vexa::Runtime& __vexa_runtime, vexa::Value prefix) override {
    try {
      return vexa::add(__vexa_runtime, vexa::add(__vexa_runtime, prefix, __vexa_runtime.string(" ")), this->name);
    }
    catch (const vexa::ReturnSignal<vexa::Value>& __vexa_return) { return __vexa_return.value(); }
  }
};
class Spanish final : public cppgc::GarbageCollected<Spanish>, public Greeter {
 public:
  Spanish(vexa::Value name) : name(name) {}
  void Trace(cppgc::Visitor* visitor) const final { Greeter::Trace(visitor); }
  const vexa::Value name;
  vexa::Value greet(vexa::Runtime& __vexa_runtime, vexa::Value prefix) override {
    try {
      return vexa::add(__vexa_runtime, vexa::add(__vexa_runtime, prefix, __vexa_runtime.string(", ")), this->name);
    }
    catch (const vexa::ReturnSignal<vexa::Value>& __vexa_return) { return __vexa_return.value(); }
  }
};
class NumberBox final : public cppgc::GarbageCollected<NumberBox> {
 public:
  NumberBox(std::int32_t value) : value(value) {}
  void Trace(cppgc::Visitor*) const {}
  std::int32_t value;
  NumberBox* operator_plus__NumberBox(vexa::Runtime& __vexa_runtime, NumberBox* other) {
    try {
      return __vexa_runtime.make<NumberBox>((this->value + other->value));
    }
    catch (const vexa::ReturnSignal<NumberBox*>& __vexa_return) { return __vexa_return.value(); }
  }
  NumberBox* operator_minus__void(vexa::Runtime& __vexa_runtime) {
    try {
      return __vexa_runtime.make<NumberBox>((-this->value));
    }
    catch (const vexa::ReturnSignal<NumberBox*>& __vexa_return) { return __vexa_return.value(); }
  }
  std::int32_t operator_spaceship__NumberBox(vexa::Runtime& __vexa_runtime, NumberBox* other) {
    try {
      return vexa::compare(this->value, other->value);
    }
    catch (const vexa::ReturnSignal<std::int32_t>& __vexa_return) { return __vexa_return.value(); }
  }
  std::int32_t operator_get__int(vexa::Runtime& __vexa_runtime, std::int32_t offset) {
    try {
      return (this->value + offset);
    }
    catch (const vexa::ReturnSignal<std::int32_t>& __vexa_return) { return __vexa_return.value(); }
  }
  void operator_set__int__int(vexa::Runtime& __vexa_runtime, std::int32_t next, std::int32_t offset) {
    try {
      (this->value = (next + offset));
    }
    catch (const vexa::ReturnSignal<void>& __vexa_return) { return; }
  }
};
class Bag final : public cppgc::GarbageCollected<Bag> {
 public:
  Bag(vexa::ArrayObject<std::int32_t>* values) : values(values) {}
  void Trace(cppgc::Visitor* visitor) const { visitor->Trace(values); }
  const cppgc::Member<vexa::ArrayObject<std::int32_t>> values;
};
class Animal : public cppgc::GarbageCollected<Animal> {
 public:
  Animal() = default;
  virtual void Trace(cppgc::Visitor*) const {}
  virtual vexa::Value speak(vexa::Runtime& __vexa_runtime) {
    try {
      return __vexa_runtime.string("base");
    }
    catch (const vexa::ReturnSignal<vexa::Value>& __vexa_return) { return __vexa_return.value(); }
  }
};
class Dog final : public Animal {
 public:
  Dog() = default;
  void Trace(cppgc::Visitor* visitor) const final { Animal::Trace(visitor); }
  vexa::Value speak(vexa::Runtime& __vexa_runtime) override {
    try {
      return vexa::add(__vexa_runtime, this->Animal::speak(__vexa_runtime), __vexa_runtime.string("!"));
    }
    catch (const vexa::ReturnSignal<vexa::Value>& __vexa_return) { return __vexa_return.value(); }
  }
};

std::int32_t importedDouble(vexa::Runtime& __vexa_runtime, std::int32_t value) {
  try {
    return (value * 2);
  }
  catch (const vexa::ReturnSignal<std::int32_t>& __vexa_return) { return __vexa_return.value(); }
}
vexa::Value importedLabel(vexa::Runtime& __vexa_runtime) {
  try {
    return __vexa_runtime.string("module");
  }
  catch (const vexa::ReturnSignal<vexa::Value>& __vexa_return) { return __vexa_return.value(); }
}
vexa::Value render(vexa::Runtime& __vexa_runtime, Meter* meter) {
  try {
    ([&]() { auto* __vexa_property_receiver = meter; auto __vexa_property_current = __vexa_property_receiver->__vexa_property_get_value(__vexa_runtime); auto __vexa_property_operand = 2; auto __vexa_property_value = (__vexa_property_current + __vexa_property_operand); __vexa_property_receiver->__vexa_property_set_value(__vexa_runtime, __vexa_property_value); return __vexa_property_value; }());
    ([&]() { auto* __vexa_property_receiver = meter; auto __vexa_property_current = __vexa_property_receiver->__vexa_property_get_value(__vexa_runtime); auto __vexa_property_value = (__vexa_property_current + 1); __vexa_property_receiver->__vexa_property_set_value(__vexa_runtime, __vexa_property_value); return __vexa_property_current; }());
    return vexa::add(__vexa_runtime, vexa::add(__vexa_runtime, vexa::add(__vexa_runtime, vexa::add(__vexa_runtime, vexa::add(__vexa_runtime, vexa::add(__vexa_runtime, __vexa_runtime.string(""), meter->__vexa_property_get_label(__vexa_runtime)), __vexa_runtime.string(":")), meter->__vexa_property_get_value(__vexa_runtime)), __vexa_runtime.string(":")), meter->__vexa_property_get_leaf(__vexa_runtime)->value), __vexa_runtime.string(""));
  }
  catch (const vexa::ReturnSignal<vexa::Value>& __vexa_return) { return __vexa_return.value(); }
}
vexa::Value greet(vexa::Runtime& __vexa_runtime, Greeter* greeter, vexa::Value prefix) {
  try {
    return greeter->greet(__vexa_runtime, prefix);
  }
  catch (const vexa::ReturnSignal<vexa::Value>& __vexa_return) { return __vexa_return.value(); }
}
std::int32_t add(vexa::Runtime& __vexa_runtime, std::int32_t value, std::int32_t delta) {
  try {
    return (value + delta);
  }
  catch (const vexa::ReturnSignal<std::int32_t>& __vexa_return) { return __vexa_return.value(); }
}
std::int32_t sumDown(vexa::Runtime& __vexa_runtime, std::int32_t value) {
  try {
    if ((value <= 0)) {
      return 0;
    }
    return (value + sumDown(__vexa_runtime, (value - 1)));
  }
  catch (const vexa::ReturnSignal<std::int32_t>& __vexa_return) { return __vexa_return.value(); }
}
vexa::Value classify(vexa::Runtime& __vexa_runtime, vexa::Value value) {
  try {
    {
      try {
      {
        auto __vexa_switch_value_0 = value;
        std::int32_t __vexa_switch_case_0 = 1;
        if (__vexa_switch_value_0 == __vexa_runtime.string("native")) { __vexa_switch_case_0 = 0; }
        switch (__vexa_switch_case_0) {
          case 0:
          {
            return __vexa_runtime.string("compiled");
          }
          default:
          {
            return __vexa_runtime.string("other");
          }
        }
      }
      } catch (const vexa::BreakSignal&) {}
    }
  }
  catch (const vexa::ReturnSignal<vexa::Value>& __vexa_return) { return __vexa_return.value(); }
}
std::int32_t guarded(vexa::Runtime& __vexa_runtime) {
  try {
    {
      std::exception_ptr __vexa_pending_completion_0;
      try {
        {
          {
            std::exception_ptr __vexa_pending_completion_1;
            try {
              try {
                vexa::throwValue(vexa::Error(__vexa_runtime.string("expected")));
              }
              catch (const std::exception& __vexa_caught_error_1) {
                auto error = __vexa_runtime.string(__vexa_caught_error_1.what());
                throw vexa::ReturnSignal<std::int32_t>(7);
              }
            } catch (...) {
              __vexa_pending_completion_1 = std::current_exception();
            }
            {
              vexa::console.log(__vexa_runtime.string("finally"));
            }
            if (__vexa_pending_completion_1) std::rethrow_exception(__vexa_pending_completion_1);
          }
        }
      } catch (...) {
        __vexa_pending_completion_0 = std::current_exception();
      }
      {
        vexa::console.log(__vexa_runtime.string("defer"));
      }
      if (__vexa_pending_completion_0) std::rethrow_exception(__vexa_pending_completion_0);
    }
  }
  catch (const vexa::ReturnSignal<std::int32_t>& __vexa_return) { return __vexa_return.value(); }
}
std::int32_t loopControl(vexa::Runtime& __vexa_runtime) {
  try {
    auto total = 0;
    for (auto value : *vexa::arrayPointer(__vexa_runtime.array<std::int32_t>({1, 2, 3}))) {
      try {
        {
          std::exception_ptr __vexa_pending_completion_2;
          try {
            {
              if ((value == 1)) {
                throw vexa::ContinueSignal();
              }
              if ((value == 3)) {
                throw vexa::BreakSignal();
              }
              (total += value);
            }
          } catch (...) {
            __vexa_pending_completion_2 = std::current_exception();
          }
          {
            (total += 10);
          }
          if (__vexa_pending_completion_2) std::rethrow_exception(__vexa_pending_completion_2);
        }
      }
      catch (const vexa::ContinueSignal&) { continue; }
      catch (const vexa::BreakSignal&) { break; }
    }
    return total;
  }
  catch (const vexa::ReturnSignal<std::int32_t>& __vexa_return) { return __vexa_return.value(); }
}
vexa::Generator<std::int32_t> sequence(vexa::Runtime& __vexa_runtime, std::int32_t limit) {
  try {
    for (std::int32_t value = 0; value < limit; value++) {
      try {
        co_yield value;
      }
      catch (const vexa::ContinueSignal&) { continue; }
      catch (const vexa::BreakSignal&) { break; }
    }
    for (auto&& __vexa_yield_value_0 : *vexa::arrayPointer(__vexa_runtime.array<std::int32_t>({limit, (limit + 1)}))) {
      co_yield vexa::convertValue<std::int32_t>(__vexa_runtime, __vexa_yield_value_0);
    }
    co_return (limit + 10);
    co_return vexa::defaultValue<std::int32_t>();
  }
  catch (const vexa::ReturnSignal<std::int32_t>& __vexa_return) { co_return __vexa_return.value(); }
}
vexa::Task<std::int32_t> asyncValue(vexa::Runtime& __vexa_runtime) {
  try {
    co_return 20;
    co_return vexa::defaultValue<std::int32_t>();
  }
  catch (const vexa::ReturnSignal<std::int32_t>& __vexa_return) { co_return __vexa_return.value(); }
}
vexa::Task<std::int32_t> doubledAsync(vexa::Runtime& __vexa_runtime) {
  try {
    co_return ((co_await asyncValue(__vexa_runtime)) * 2);
    co_return vexa::defaultValue<std::int32_t>();
  }
  catch (const vexa::ReturnSignal<std::int32_t>& __vexa_return) { co_return __vexa_return.value(); }
}
vexa::Task<vexa::Value> delay(vexa::Runtime& __vexa_runtime, double ms) {
  try {
    return vexa::Task<vexa::Value>::create(__vexa_runtime, [=, &__vexa_runtime](auto resolve, auto reject) mutable { __vexa_runtime.setTimeout(resolve, ms); });
  }
  catch (const vexa::ReturnSignal<vexa::Task<vexa::Value>>& __vexa_return) { return __vexa_return.value(); }
}

int main() {
  vexa::Runtime runtime;
  vexa::console.log(runtime.string("module"), importedLabel(runtime), importedDouble(runtime, 6));
  vexa::console.log(runtime.string("functions"), add(runtime, 4, 1), add(runtime, 4, 3), sumDown(runtime, 4));
  auto counter = runtime.make<Counter>(1, runtime.string("cpu"), runtime.make<Leaf>(9));
  vexa::console.log(runtime.string("interface"), render(runtime, counter), counter->add(runtime, 3));
  auto greeters = runtime.array<Greeter*>({runtime.make<English>(runtime.string("Ada")), runtime.make<Spanish>(runtime.string("Luz"))});
  vexa::console.log(runtime.string("dispatch"), greet(runtime, vexa::arrayGet(vexa::arrayPointer(greeters), 0), runtime.string("Hello")), greet(runtime, vexa::arrayGet(vexa::arrayPointer(greeters), 1), runtime.string("Hola")));
  auto box = runtime.make<NumberBox>(2)->operator_plus__NumberBox(runtime, runtime.make<NumberBox>(3));
  vexa::assignWith(box, [&](auto __vexa_compound_target) { return __vexa_compound_target->operator_plus__NumberBox(runtime, runtime.make<NumberBox>(1)); });
  auto negative = box->operator_minus__void(runtime);
  auto less = (runtime.make<NumberBox>(1)->operator_spaceship__NumberBox(runtime, runtime.make<NumberBox>(2)) < 0);
  auto indexed = box->operator_get__int(runtime, 4);
  box->operator_set__int__int(runtime, 8, 2);
  vexa::console.log(runtime.string("operators"), box->value, negative->value, less, indexed);
  vexa::console.log(runtime.string("inheritance"), runtime.make<Dog>()->speak(runtime));
  auto shared = runtime.array<std::int32_t>({1, 2});
  auto firstBag = runtime.make<Bag>(shared);
  auto secondBag = runtime.make<Bag>(shared);
  vexa::push(vexa::arrayPointer(firstBag->values), 3);
  vexa::console.log(runtime.string("shared"), static_cast<double>(vexa::arrayPointer(secondBag->values)->size()), vexa::join(vexa::arrayPointer(secondBag->values), runtime.string("|")));
  auto numbers = runtime.array<std::int32_t>({1, 2, 3, 4});
  auto transformed = vexa::filter(runtime, vexa::arrayPointer(vexa::map(runtime, vexa::arrayPointer(numbers), [&](auto it) { return (it * 3); })), [&](auto it) { return ((it % 2) == 0); });
  auto reduced = vexa::reduce(vexa::arrayPointer(transformed), [&](std::int32_t total, std::int32_t item) { return (total + item); }, 0);
  vexa::unshift(vexa::arrayPointer(numbers), 0);
  auto shifted = vexa::shift(vexa::arrayPointer(numbers));
  auto popped = vexa::pop(vexa::arrayPointer(numbers));
  vexa::reverse(vexa::arrayPointer(numbers));
  vexa::console.log(runtime.string("arrays"), vexa::join(vexa::arrayPointer(transformed), runtime.string(",")), reduced, shifted, popped, vexa::join(vexa::arrayPointer(numbers), runtime.string(",")));
  vexa::console.log(runtime.string("array-copy"), vexa::join(vexa::arrayPointer(vexa::slice(runtime, vexa::arrayPointer(numbers), 0, 2)), runtime.string("|")), vexa::join(vexa::arrayPointer(vexa::concat(runtime, vexa::arrayPointer(numbers), 8, 9)), runtime.string("|")));
  vexa::console.log(runtime.string("array-string"), vexa::toString(runtime.array<std::int32_t>({1, 2})));
  auto mixed = runtime.array<vexa::Value>({vexa::convertValue<vexa::Value>(runtime, 1), vexa::convertValue<vexa::Value>(runtime, runtime.string("two")), vexa::convertValue<vexa::Value>(runtime, true)});
  vexa::push(vexa::arrayPointer(mixed), vexa::convertValue<vexa::Value>(runtime, runtime.string("three")));
  vexa::console.log(runtime.string("mixed"), vexa::includes(vexa::arrayPointer(mixed), vexa::convertValue<vexa::Value>(runtime, runtime.string("two"))), vexa::indexOf(vexa::arrayPointer(mixed), vexa::convertValue<vexa::Value>(runtime, true)), vexa::join(vexa::arrayPointer(mixed), runtime.string("|")));
  auto key = runtime.string("score");
  auto base = runtime.record({{"name", vexa::convertValue<vexa::Value>(runtime, runtime.string("Ada"))}, {"stale", vexa::convertValue<vexa::Value>(runtime, true)}});
  auto record = ([&]() { auto* __vexa_record = runtime.record(); vexa::recordSpread(__vexa_record, base); vexa::recordSet(runtime, __vexa_record, vexa::propertyKey(key), vexa::convertValue<vexa::Value>(runtime, 40)); vexa::recordSet(runtime, __vexa_record, "score", vexa::convertValue<vexa::Value>(runtime, 41)); vexa::recordSet(runtime, __vexa_record, "nested", vexa::convertValue<vexa::Value>(runtime, runtime.record({{"active", vexa::convertValue<vexa::Value>(runtime, true)}}))); return __vexa_record; }());
  ([&]() { auto* __vexa_property_receiver = record; auto __vexa_property_key = vexa::propertyKey(key); auto __vexa_property_current = vexa::recordGet<vexa::Value>(runtime, __vexa_property_receiver, __vexa_property_key); auto __vexa_property_operand = 1; auto __vexa_property_value = vexa::add(runtime, __vexa_property_current, __vexa_property_operand); vexa::recordSet(runtime, __vexa_property_receiver, __vexa_property_key, __vexa_property_value); return __vexa_property_value; }());
  ([&]() { auto* __vexa_property_receiver = vexa::recordGet<vexa::RecordObject*>(runtime, record, "nested"); auto __vexa_property_value = false; vexa::recordSet(runtime, __vexa_property_receiver, "active", __vexa_property_value); return __vexa_property_value; }());
  auto hadName = vexa::recordHas(record, vexa::propertyKey(runtime.string("name")));
  auto removed = vexa::recordDelete(record, "stale");
  vexa::console.log(runtime.string("record"), vexa::recordGet<vexa::Value>(runtime, record, "name"), vexa::recordGet<std::int32_t>(runtime, record, "score"), vexa::recordGet<bool>(runtime, vexa::recordGet<vexa::RecordObject*>(runtime, record, "nested"), "active"), hadName, removed, vexa::recordGetOptional(record, "name"));
  vexa::console.log(runtime.string("enum"), Permission::None, Permission::All);
  {
    try {
    switch (Permission::All) {
      case Permission::All:
      {
        vexa::console.log(runtime.string("switch"), classify(runtime, runtime.string("native")));
        break;
      }
      default:
      {
        vexa::console.log(runtime.string("switch"), runtime.string("wrong"));
      }
    }
    } catch (const vexa::BreakSignal&) {}
  }
  vexa::console.log(runtime.string("strings"), vexa::toUpperCase(vexa::trim(runtime.string("  Vexa  "))), vexa::stringIncludes(runtime.string("language"), runtime.string("gua")));
  vexa::console.log(runtime.string("math-regex"), vexa::Math::max(3, 7), vexa::Math::round(2.6), vexa::regexTest(vexa::RegExp("vexa", "i"), runtime.string("VEXA")));
  vexa::console.log(runtime.string("control"), loopControl(runtime));
  vexa::console.log(runtime.string("errors"), guarded(runtime));
  auto iterator = sequence(runtime, 2);
  auto firstYield = iterator.next();
  auto yieldedTotal = firstYield.value;
  for (auto value : iterator) {
    try {
      (yieldedTotal += value);
    }
    catch (const vexa::ContinueSignal&) { continue; }
    catch (const vexa::BreakSignal&) { break; }
  }
  auto finished = iterator.next();
  vexa::console.log(runtime.string("generator"), firstYield.done, firstYield.value, yieldedTotal, finished.done);
  auto recovered = vexa::promiseCatch(runtime, vexa::rejectedTask<vexa::Value>(runtime, vexa::Error(runtime.string("bad"))), [&](vexa::Value reason) { return 9; });
  auto all = (vexa::promiseAll(runtime, vexa::arrayPointer(runtime.array<vexa::Task<std::int32_t>>({vexa::resolvedTask(runtime, 1), vexa::resolvedTask(runtime, 2)})))).get();
  auto chained = (vexa::promiseThen(runtime, vexa::resolvedTask(runtime, 3), [&](std::int32_t value) { return (value + 4); })).get();
  vexa::console.log(runtime.string("promises"), (recovered).get(), vexa::arrayGet(vexa::arrayPointer(all), 0), vexa::arrayGet(vexa::arrayPointer(all), 1), chained);
  vexa::console.log(runtime.string("async"), (asyncValue(runtime)).get(), (doubledAsync(runtime)).get());
  auto cancelledInterval = runtime.setInterval([&]() { return vexa::console.log(runtime.string("unexpected interval")); }, 0);
  runtime.clearInterval(cancelledInterval);
  vexa::console.log(runtime.string("interval"), runtime.string("cancelled"));
  (delay(runtime, 0)).get();
  vexa::console.log(runtime.string("timeout"), runtime.string("done"));
  runtime.runEventLoop();
  return 0;
}
